### ISSUE TITLE
How to use tags

### ISSUE THREAD

**Issue by MarcelJurtz** [samanyougarg/hanuman#12]
Hello, thanks for your great template!

I migrated my blog from wordpress and I'd like to use my tags / categories. How can I do that? The tags are already being displayed, but clicking them leads to the home page. Also, categories aren't shown at all. Thanks!

**Comment by samanyougarg** [comment]
Hi
Tag pages haven't been implemented yet. I will try to implement it asap.
Thanks

**Comment by MarcelJurtz** [comment]
Alright, great!

**Comment by samanyougarg** [comment]
Hey!
Tag page has been added.
Thanks

**Comment by MarcelJurtz** [comment]
Awesome, thank you!
