### ISSUE TITLE
Multiple Author's

### ISSUE THREAD

**Issue by JMGama** [samanyougarg/hanuman#13]
## Hello, before anything thanks for the hanuman theme, its amazing!
I want to add multiple authors, but i don't know how can I assign a different author for the posts, how could i do that? :thinking: 
I know the Author is in the author.yml but how can i add more and assign them to the posts.

**Comment by samanyougarg** [comment]
Hi,
I am glad you liked the theme.
I have added the functionality for adding multiple authors. 
You can add multiple authors in _data/authors.yml.
Basically, you just need to use the author tag in the front matter of each post.
See the sample posts for examples.
