### ISSUE TITLE
links of the posts at the tag's page are not redirecting.

### ISSUE THREAD

**Issue by JMGama** [samanyougarg/hanuman#14]
links of the posts at the tag's page are not redirecting.
-----------------------------------------------
At the /tags page the Posts that are showing and try to redirect are not working, because the base url isn't added before the post url.

Example:

> https://samanyougarg.com/hanuman/tags/#code

if you click on the **code** post it redirect to that post

> https://samanyougarg.com/code

and if you see, it send us to 404 error page.....
the right URL for the post need to have the base URL added before the post URL, like this:

> https://samanyougarg.com/hanuman/code

I think the error is at the `tags.md`
:wink:

**Comment by samanyougarg** [comment]
Hi @JMGama,
Thanks for reporting the bug. It has been fixed now.
