### ISSUE TITLE
Title with button for Home page

### ISSUE THREAD

**Issue by JMGama** [samanyougarg/hanuman#16]
Hi, im actually trying to make the top bar title 'logo-hanuman' a button or something that can go to the Home page whenever it gets clicked, but i'm really bad with CSS :sweat_smile: , wen I managed to make it a `<a></a>` tag it gets stuck in the Left side of the bar, can u help me with that?

**Comment by samanyougarg** [comment]
Hi
You need to add class my0 mx-auto to the a tag. Check the latest commit.
