### ISSUE TITLE
"/" baseurl changes to "" when deployed to GitHub Pages

### ISSUE THREAD

**Issue by nicholaschuayunzhi** [samanyougarg/hanuman#3]
Config used was ` baseurl: "/" ` and works fine locally. However, when deployed to GitHub Pages, the baseurl is changed to "" and href for navigation and footer will not have the "/" prepended.

With some research I stumbled on this issue https://github.com/github/pages-gem/issues/350 and a possible solution to this can be found [here](https://github.com/github/pages-gem/issues/350#issuecomment-317429640)

Would like your thoughts on this solution as I've only tested on a user site.

**Comment by samanyougarg** [comment]
Hi

I just tried deploying to Github Pages on a new site. It seems to work fine.

What did you set as your url in _config.yml?

**Comment by nicholaschuayunzhi** [comment]
Hi there,

when i set the url as "https://nicholaschuayunzhi.github.io" and base url "/" it works fine locally but when deployed to ghpages,  the href of my links don't have "/" prepended.

**Comment by samanyougarg** [comment]
You can leave the base url as "". It should work on local as well as on Github Pages. Try it and let me know.
Thanks

**Comment by nicholaschuayunzhi** [comment]
Hi there!

I tried leaving baseurl as "" and it does not work locally. I've also tried using the "/" as suggested and works locally but does not work when deployed to Github Pages.

I've updated my [repository](https://github.com/nicholaschuayunzhi/nicholaschuayunzhi.github.io). You can refer to the config file there. The site has also been deployed to gh pages as a user site.

The error arises when i try to use the side bar from my about page. https://nicholaschuayunzhi.github.io/about/

When i click about on the side bar it redirects me to https://nicholaschuayunzhi.github.io/about/about

**Comment by samanyougarg** [comment]
How are you deploying the site to Github Pages?
I just tried deploying using travis as well as pushing contents of site-pages to the gh-pages branch of the repository and it worked fine.

**Comment by nicholaschuayunzhi** [comment]
I'm not too sure what you're asking here sorry - I'm a bit new to this. I'm building from master branch.

I read in the readme that i'm supposed to push the _site folder? but its under the gitignore. Am i doing something wrongly?

I'm not using travis to deploy.

**Comment by samanyougarg** [comment]
No worries.
If you installed the theme using method 1, you need to push the contents of the destination folder (mentioned in _config.yml. eg - destination: ../hanuman-pages/) to the gh-pages branch(if project page) or master branch(if user page) of your repository.
If you installed the theme using Ruby Gem method, you need to push the contents of _site folder.
I will make the instructions more clear.

**Comment by nicholaschuayunzhi** [comment]
Hmm, i tried the first method but i still get the same error.

Here are the steps i did:
1) `$ git clone https://github.com/samanyougarg/hanuman.git`
2) updated config.yml [gist](https://gist.github.com/nicholaschuayunzhi/c6e6dea906e1e066c3ccfad231edecf4)
3) `$ bundle exec jekyll build`
4) push the destination folder to my repo (/hanuman-pages/) https://github.com/nicholaschuayunzhi/nicholaschuayunzhi.github.io

<del>I still get the same error mentioned in https://github.com/samanyougarg/hanuman/issues/3#issuecomment-352199771</del>

EDIT: Want to clarify that it works fine locally.
EDIT2: Added the build step.

**It works fine now! Thanks for your patience :)**

**Comment by nicholaschuayunzhi** [comment]
Would like to add the error i made before was:

1) `$ git clone https://github.com/samanyougarg/hanuman.git`
2) updated config.yml gist
3) `$ bundle exec jekyll build`
4) push the cloned repo into my repo
